
version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/node:16.15.0"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install 
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            nvm use 16.15.0 && npm run frontend:build 
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App UI
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy App API
          command: |
            eb setenv AWS_ACCESS_KEY_ID
            eb setenv AWS_BUCKET
            eb setenv AWS_DEFAULT_REGION
            eb setenv AWS_REGION
            eb setenv AWS_SECRET_ACCESS_KEY
            eb setenv DB_PORT
            eb setenv JWT_SECRET
            eb setenv POSTGRES_DB
            eb setenv POSTGRES_HOST
            eb setenv POSTGRES_PASSWORD
            eb setenv POSTGRES_USERNAME
            eb setenv URL
            npm run backend:deploy